minimatitle: Mi sitio
author: David Toro
email: eldavidtoro96@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Mi sitio web para lenguaje de marcas

# social links
twitter_username: www.twitter.com
github_username:  www.github.com

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
